# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8416d4587cc3f462dcebfef7c2e746652427ce421d7db164f3144c31f1e03ab2b5fdeb2020921858a63c23f18857d948aa935c4b2896da46367d82fc364dfba

test:
  secret_key_base: 14e3a2866055c14c4186e4e12fa11edc6bb15950d94b602d377c4fd6a7f5fa7ed561ff2316068d3e89a3fe256f2d2f3d926f7a1dfdcd6088d19219f7f6eb7fa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
